server:
  port: 8084
feign: 
  hystrix: 
    enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
spring:
  application:
    name: letdoit-feign